// <auto-generated />
using ContactBook.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactBook.API.Migrations
{
    [DbContext(typeof(EmployeeInfoContext))]
    partial class EmployeeInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("ContactBook.API.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            EmailAddress = "jd@gmail.com",
                            EmployeeId = 0,
                            MobileNumber = "123-456-7890"
                        },
                        new
                        {
                            ContactId = 2,
                            EmailAddress = "js@gmail.com",
                            EmployeeId = 0,
                            MobileNumber = "987-654-3210"
                        },
                        new
                        {
                            ContactId = 3,
                            EmailAddress = "aj@gmail.com",
                            EmployeeId = 0,
                            MobileNumber = "555-555-5555"
                        });
                });

            modelBuilder.Entity("ContactBook.API.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Software Engineer",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Project Manager",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            Designation = "UX Designer",
                            Name = "Alice Johnson"
                        });
                });

            modelBuilder.Entity("ContactBook.API.Entities.Contact", b =>
                {
                    b.HasOne("ContactBook.API.Entities.Employee", "Employee")
                        .WithMany("ContactDetails")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ContactBook.API.Entities.Employee", b =>
                {
                    b.Navigation("ContactDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
